### ISSUE TITLE
Proposition to improve the Operation type

### ISSUE THREAD

**Issue by tymonx** [evanphx/json-patch#134]
Current `type Operation map[string]*json.RawMessage` definition is... well... literally ugly.

It has several issues:
- You cannot easily create the `Patch` type by hand
- The map value contains pointer to slice bytes. That means extra unnecessary indirect jump (pointer to pointer) and allocation
- It forces user to relay on JSON library (currently the standard one) used by the project. It impacts performance. For example someone want to use more efficient JSON library to unmarshal JSON Patch array of operations
- It needs extra unnecessary step (every time) to retrieve basic information from the `Operation` type

The proposition is to keep this simple and cleaner:
```go
// Operation defines a single atomic operation to apply to a target.
type Operation struct {
	Op    Op              `json:"op"`
	Path  string          `json:"path"`
	From  string          `json:"from,omitempty"`
	Value json.RawMessage `json:"value,omitempty"`
}

// These constants defines operation types to perfom.
const (
	Unknown Op = iota // in case when someone forget to explitly set the op field
	Add
	Remove
	Replace
	Move
	Copy
	Test
)

// Op defines an operation type to perform.
type Op int

var gToString = map[Op]string{ //nolint: gochecknoglobals
	Add:     "add",
	Remove:  "remove",
	Replace: "replace",
	Move:    "move",
	Copy:    "copy",
	Test:    "test",
}

var gFromString = map[string]Op{ //nolint: gochecknoglobals
	"add":     Add,
	"remove":  Remove,
	"replace": Replace,
	"move":    Move,
	"copy":    Copy,
	"test":    Test,
}

// String returns op as a string.
func (o Op) String() string {
	return gToString[o]
}

// UnmarshalText decodes text to op.
func (o *Op) UnmarshalText(data []byte) error {
	if v, ok := gFromString[string(data)]; ok {
		*o = v
		return nil
	}

	return rterror.New("invalid op value", string(data))
}

// MarshalText encodes op to text.
func (o Op) MarshalText() ([]byte, error) {
	return []byte(o.String()), nil
}
```

**Comment by evanphx** [comment]
Moving Operation to being a struct I think is probably fine, but I'm unsure why the `Op` type is needed in this cleanup. Could you explain the justification for that more?

**Comment by tymonx** [comment]
Simple. Auto-validation for `op` during `UnmarshalJSON`. Because many JSON libraries (including the standard one) calls the `UnmarshalText` method if available for JSON strings.

Also an integer type is faster for `switch - case` if someone want to use it. For example to filter/reject operations before call the `Apply` method. It is useful for JSON RESTful APIs.

**Comment by evanphx** [comment]
Gotcha. Ok, i'd be fine with this change.

**Comment by tymonx** [comment]
If you want, I can provide a Pull Request with necessary chances.

**Comment by evanphx** [comment]
@tymonx Sure that would be great!

**Comment by kszafran** [comment]
@tymonx Will you be working on this? If not, I could contribute a PR myself, since this would also be useful to me.

**Comment by kszafran** [comment]
@evanphx I can work on this, but first I'd like to double check that you're OK with this quite fundamental change. Besides the change in behavior that I mentioned in my previous comment, this is an obvious breaking change for anyone who was constructing `jsonpatch.Patch` objects directly instead of unmarshaling them (e.g. `jsonpatch.Patch{jsonpatch.Operation{"path": ...}}`).

Perhaps this is a good candidate for v6?

Also, I think making this change will make it easier to resolve https://github.com/evanphx/json-patch/issues/86 (see my latest comment).

Moreover, it might help with https://github.com/evanphx/json-patch/issues/136, since we should then be able to validate the patch itself (when unmarshaling it), and so any error from `Apply` would be because the patch failed to apply. Currently, an error from `Apply` might mean either that the patch is invalid, or that it failed to apply. It's an important distinction, and e.g. in a REST API you might want to return 400 or 422 depending on the cause.

**Comment by evanphx** [comment]
@kszafran You make a very good point about it breaking anyone that constructs a patch by hand. We can't break that.

Given the large nature of the change, I feel like it needs to be justified in terms of improved functionality or bugs fixed. It's not possible to justify a v6 just on code cleanup.
