### ISSUE TITLE
Reason for skipping operations on empty documents?

### ISSUE THREAD

**Issue by chmorgan** [evanphx/json-patch#155]
This one had me stuck for an hour or two or so so figured I'd raise it here.

v5 skips operating on documents of 0 length, there is a test for it as well to confirm that operations on "" result in "".

I reviewed https://datatracker.ietf.org/doc/html/rfc6902, and the docs for json-patch and it isn't clear why operations on an empty document wouldn't be considered valid.

I'd argue that "" is effectively "{}". In my use case I'm introducing a new database sub-field and using patches to alter it. As such it isn't present in the json object at all, so its effectively "" for existing rows.

Thoughts on treating "" as "{}"? Alternatively, thoughts on how to indicate dropping patches to the user? json-patch is silently dropping patches for op: "add" and "replace", which would seem to be valid in the initial case of an empty document.

lmk and I can see about pushing a PR up. Would like to save the next person a couple of hours of debug time.

**Comment by kszafran** [comment]
This is strange. I would have expected `""` to cause an error, since it's not a valid JSON. I don't think `""` should be treated as `{}`. That could also result in surprising behavior. In my opinion `""` should return an error, and if someone wants to treat is as an empty JSON they can just add `if input == "" { input = "{}" }` before calling `Apply`.

But since there's a test for it, maybe there was a good reason to just ignore `""`?

**Comment by chmorgan** [comment]
Yeah there is a test and inside of ApplyWithIndenting or something there is
a if len(doc) == 0 check that returns early.

And to be clear by “” I mean an empty string, not a string with a single
space in it.

**Comment by chmorgan** [comment]
@evanphx thoughts on how to handle this? I can open a PR with whatever you think is a reasonable change (if you think a change should be made)

**Comment by evanphx** [comment]
I realize it's a bit ambiguous but I'm not interested in changing the behavior at this point because it will introduce a subtle deviation in behavior with no real upside.
