### ISSUE TITLE
provide a way to change json library 

### ISSUE THREAD

**Issue by zysimplelife** [evanphx/json-patch#157]
Hi

As we probable known, golang json library has no really good performance.   as we have tested, it is actually bad performance when come to big or large document.  in order to mitigate the problem, some library has provided improvement and looks promising.  for example  https://github.com/goccy/go-json)
However, it is not possible to replace json library in this project, without changing the code.  I am thinking it would be very helpful if those interface can be extend to support the "interface{}" rather than just "byte[]", to speed up the decoding part

for example 

DecodePatchInterface(interface{})

**Comment by evanphx** [comment]
Providing the ability to change the package isn't a great API, if we need to change the base package to something other than  `encoding/json`, i'm open to it. If you want to submit a PR that does that with benchmarking to show the differences, please do!

As for an decode function, I suppose you want this so that it uses a different package for decoding and then passes in the decoded result? I'd prefer to avoid that, but I would consider it if you go through how it would look a bit more.
