### ISSUE TITLE
Move / replace operations should fail if origin does not exist

### ISSUE THREAD

**Issue by jkodumal** [evanphx/json-patch#18]
According to RFC 6902, a `move` operation should fail if the `from` location does not exist. The spec also states that a `replace` operation should fail if the `path` does not exist. 

My testing shows that neither of these errors are caught at the moment.

**Comment by Loushu** [comment]
This issue should be reopened, as "replace" operation still doesn't fail if "path" doesn't exist.

**Comment by evanphx** [comment]
@Loushu Can you give me an example of a document and patch that should work but doesn't?

**Comment by Loushu** [comment]
@evanphx I'm trying to "replace" a value at a path that doesn't exist. Instead of failing the operation succeeds and "add"s a value at the path. Example:
Document: 
{ "Metadata": {	} }
Patch:
[
  {
    "op": "replace",
    "path": "/Metadata/key1",
    "value": "val1"
  }
]
Expected result is a failure to apply patch since key1 doesn't exist
Actual result: {"Metadata":{"key1":"val1"}}
