### ISSUE TITLE
Apply JSON Patch failed

### ISSUE THREAD

**Issue by pytimer** [evanphx/json-patch#68]
Hi, all

I want to use `JSON Patch` to add a name is `injector.test.io/status` key into the json document, but it failed.

error logs:
```sh
jsonpatch add operation does not apply: doc is missing path: "/annotations/injector.test.io/status"
```

But i rename this key is `injector.test.io.status`, it works well. 

I want to know how to do if want to add similar to `xx/yy` key into json document? Thanks. 

Below is my demo code:

```go
package main

import (
	"fmt"

	jsonpatch "github.com/evanphx/json-patch"
)

func main() {
	original := []byte(`{"annotations": {"injector.test.io/inject": "true"}}`)
	patchJSON := []byte(`[
		{"op": "add", "path": "/annotations/injector.test.io/status", "value": "true"}
	]`)

	patch, err := jsonpatch.DecodePatch(patchJSON)
	if err != nil {
		panic(err)
	}

	modified, err := patch.Apply(original)
	if err != nil {
		panic(err)
	}

	fmt.Printf("Original document: %s\n", original)
	fmt.Printf("Modified document: %s\n", modified)
}
```

**Comment by evanphx** [comment]
Because you're trying to use / in the keys themselves, it's really confusing the JSON patch code. I'm not sure how you'd do this as the RFC doesn't really make it possible. The easiest thing might be to use a merge patch. That's where you just specify the subset that you want to change and call `jsonpatch.MergePatch`. The RFC is here https://tools.ietf.org/html/rfc7396.

**Comment by pytimer** [comment]
Thanks for you reply. I will try `jsonpatch.MergePatch`. 
I'm beginner about it, so the idea may not be right.
